general:
steps:
  mtaBuild:
    buildTarget: 'CF'
      cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: '2851d1c7trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
